image: python:latest

cache:
  paths:
    - venv/

stages:
  - compile
  - test
  - deploy

before_test:
  stage: compile
  script:
    - python --version # for debugging
    - pip install virtualenv flask

test-setup:
  stage: test
  script:
    - echo "Testing running of setup file"
    - # python3 setup.py

test-file:
  stage: test
  script:
    - echo "This job tests our main .py file."
    # - python our_file.py
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "I will deploy now to Heroku."
