image: python:latest

cache:
  paths:
    - venv/

stages:
  - compile
  - test
  - deploy

before_test:
  stage: compile
  script:
    - python --version # for debugging
    - pip install virtualenv flask

test-setup:
  stage: test
  script:
    - echo "Testing running of setup file"
    # - python3 setup.py # dunno if this is necessary

test-processor:
  stage: test
  script:
    - pip install pytest_yaml
    - echo "This job tests our main test_query_processory.py file."
    - pytest --version # for debugging
    - python -m py.test ./tests/test_query_processor.py # or include python3 -m (in front)

deploy-prod:
  stage: deploy
  script:
    - echo "I will deploy now to Heroku." # then we deploy from here...
