image: python:latest

cache:
  paths:
    - venv/

stages:
  - compile
  - test
  - deploy

before_test:
  stage: compile
  script:
    - python --version # for debugging
    - pip install virtualenv
    - pip install -r requirements.txt

test-setup:
  stage: test
  script:
     - pwd
     - ls -l
     - export PYTHONPATH="$PYTHONPATH:."
     - python -c "import sys;print(sys.path)"
     - echo "Testing running of setup file"
     - python --version # for debugging
     - python -m pytest
     

test-processor:
  stage: test
  script:
    #- pip install pytest_yaml
    #- pip install Flask
    - python --version # for debugging
    - python -m pytest
    - python --version # for debugging
    - echo "This job tests our main test_query_processory.py file."
    - pytest --version # for debugging
    #- py.test ./tests/test_query_processor.py # or include python3 -m (in front)
    - python -m pytest ./tests/test_query_processor.py

deploy-prod:
  stage: deploy
  script:
    - echo "I will deploy now to Heroku." # then we deploy from here...

  #for adding docker image later. to be tested
  #default:
    #image: ruby:2.7.4
